[build]
  publish = "."
  command = "echo 'No build required'"
  functions = "netlify/functions"

[dev]
  targetPort = 8080
  port = 8888

[[redirects]]
  from = "/.netlify/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
